let Lvl1 = [
  { word: "مشکل", IsWordSolved: false, IsHintBought: false, IsHintBought: false, Hint: "مترادف بدبختی و سختی" },
  { word: "آپارتمان", IsWordSolved: false, IsHintBought: false, Hint: "مکانی برای زندگی" },
  { word: "فولاد", IsWordSolved: false, IsHintBought: false, Hint: "یک آلیاژ" },
  { word: "ارتش", IsWordSolved: false, IsHintBought: false, Hint: "یک واحد نظامی" },
  { word: "مازندران", IsWordSolved: false, IsHintBought: false, Hint: "نام یکی از استان های ایران" },
  { word: "شهرستان", IsWordSolved: false, IsHintBought: false, Hint: "کوچکتر از استان" },
  { word: "فرودگاه", IsWordSolved: false, IsHintBought: false, Hint: "مانند ترمینال" },
  { word: "تونل", IsWordSolved: false, IsHintBought: false, Hint: "مشابه زیرگذر" },
  { word: "آبادی", IsWordSolved: false, IsHintBought: false, Hint: "مترادف روستا یا شهر" },
  { word: "فرمانده", IsWordSolved: false, IsHintBought: false, Hint: "کسی که دستور میدهد" },
];
let Lvl2 = [
  { word: "ماشین", IsWordSolved: false, IsHintBought: false, Hint: "یک وسیله نقلیه" },
  { word: "موتور", IsWordSolved: false, IsHintBought: false, Hint: "یک وسیله نقلیه" },
  { word: "قطار", alt: "قاطر", IsWordSolved: false, IsHintBought: false, Hint: "مشابه مترو" },
  { word: "موکت", IsWordSolved: false, IsHintBought: false, Hint: "زیر پای هر ایرانی" },
  { word: "کلاه", alt: "هلاک-کاله", IsWordSolved: false, IsHintBought: false, Hint: "پوشیدنی" },
  { word: "کشور", alt: "شوکر", IsWordSolved: false, IsHintBought: false, Hint: "به معنی سرزمین" },
  { word: "پلنگ", IsWordSolved: false, IsHintBought: false, Hint: "حیوان درنده" },
  { word: "پلیس", IsWordSolved: false, IsHintBought: false, Hint: "برقرار کننده نظم و امنیت" },
  { word: "کمان", IsWordSolved: false, IsHintBought: false, Hint: "سلاح سرد" },
];
let Lvl3 = [
  { word: "هلیکوپتر", IsWordSolved: false, IsHintBought: false, Hint: "مترادف بالگرد" },
  { word: "دوچرخه", IsWordSolved: false, IsHintBought: false, Hint: "دو چرخ دارد" },
  { word: "رایانه", alt: "یارانه", IsWordSolved: false, IsHintBought: false, Hint: "مترادف کامپیوتر" },
  { word: "جنگنده", IsWordSolved: false, IsHintBought: false, Hint: "پرواز میکنه" },
  { word: "کمربند", IsWordSolved: false, IsHintBought: false, Hint: "نمیذاره شلوارت بیفته" },
  { word: "پرسپولیس", IsWordSolved: false, IsHintBought: false, Hint: "سرخپوشان" },
  { word: "پاسارگاد", IsWordSolved: false, IsHintBought: false, Hint: "بنای تاریخی" },
  { word: "کامیون", IsWordSolved: false, IsHintBought: false, Hint: "وزن سنگین جابجا میکنه" },
  { word: "ساختمان", IsWordSolved: false, IsHintBought: false, Hint: "سازه" },
];
let Lvl4 = [
  { word: "زندان", IsWordSolved: false, IsHintBought: false, Hint: "جای تبهکاران" },
  { word: "هواپیما", IsWordSolved: false, IsHintBought: false, Hint: "بال داره دم هم داره" },
  { word: "نفتکش", IsWordSolved: false, IsHintBought: false, Hint: "تو دریا حرکت میکنه" },
  { word: "تریلی", IsWordSolved: false, IsHintBought: false, Hint: "تو جاده حرکت میکنه" },
  { word: "مشتری", IsWordSolved: false, IsHintBought: false, Hint: "در دکان و در منظومه شمسی پیدا میشه" },
  { word: "آسفالت", IsWordSolved: false, IsHintBought: false, Hint: "رنگش سیاهه" },
  { word: "استقلال", IsWordSolved: false, IsHintBought: false, Hint: "کیسه" },
  { word: "بیستون", IsWordSolved: false, IsHintBought: false, Hint: "" },
  { word: "عنکبوت", IsWordSolved: false, IsHintBought: false, Hint: "پا زیاد داره" },
  { word: "لشکر", IsWordSolved: false, IsHintBought: false, Hint: "اینهمه    آمده به عشق رهبر آمده" },
];
let Lvl5 = [
  { word: "گردان", IsWordSolved: false, IsHintBought: false, Hint: "متشکل از 700 نفر" },
  { word: "گوشی", IsWordSolved: false, IsHintBought: false, Hint: "همین الان تو دستته" },
  { word: "حمام", IsWordSolved: false, IsHintBought: false, Hint: "محل شست و شو" },
  { word: "آینه", IsWordSolved: false, IsHintBought: false, Hint: "پشتش جیوه است" },
  { word: "کبوتر", IsWordSolved: false, IsHintBought: false, Hint: "دونه میخوره" },
  { word: "زندگی", IsWordSolved: false, IsHintBought: false, Hint: "با زنده موندن فرق داره" },
  { word: "خانواده", IsWordSolved: false, IsHintBought: false, Hint: "مهم ترین چیز هر انسانه" },
  { word: "مشروب", IsWordSolved: false, IsHintBought: false, Hint: "خوردنش حرامه" },
  { word: "دارو", IsWordSolved: false, IsHintBought: false, Hint: "حالتو خوب میکنه" },
  { word: "گاومیش", IsWordSolved: false, IsHintBought: false, Hint: "شیر و گوشت داره" },
];
let Lvl6 = [
  { word: "یورش", alt: "یورش-شوری", IsWordSolved: false, IsHintBought: false, Hint: "مترادف حمله" },
  { word: "زمین", IsWordSolved: false, IsHintBought: false, Hint: "یه سیاره" },
  { word: "خورشید", IsWordSolved: false, IsHintBought: false, Hint: "دارای نور" },
  { word: "مریخ", alt: "خمیر", IsWordSolved: false, IsHintBought: false, Hint: "به فارسی میشه بهرام" },
  { word: "آسمان", IsWordSolved: false, IsHintBought: false, Hint: "آبی رنگه" },
  { word: "کاشانه", IsWordSolved: false, IsHintBought: false, Hint: "خانه" },
  { word: "ماشک", IsWordSolved: false, IsHintBought: false, Hint: "خوراکی" },
  { word: "عدسی", alt: "سعید", IsWordSolved: false, IsHintBought: false, Hint: "هم خوراکیه هم وسیله است" },
  { word: "بوقلمون", IsWordSolved: false, IsHintBought: false, Hint: "گوشتش گرونه" },
  { word: "حلزون", IsWordSolved: false, IsHintBought: false, Hint: "مثل لاکپشت کنده" },
];
let Lvl7 = [
  { word: "کلید", IsWordSolved: false, IsHintBought: false, Hint: "به قفل ربط داره" },
  { word: "مسیر", IsWordSolved: false, IsHintBought: false, Hint: "مترادف راه" },
  { word: "مترو", alt: "مروت-تورم", IsWordSolved: false, IsHintBought: false, Hint: "زیر زمینه" },
  { word: "مسافرت", IsWordSolved: false, IsHintBought: false, Hint: "موقع 13 بدر انجامش میدی" },
  { word: "توشه", IsWordSolved: false, IsHintBought: false, Hint: "بقچه" },
  { word: "کرسی", alt: "سیرک-ریسک", IsWordSolved: false, IsHintBought: false, Hint: "روش میشینی" },
  { word: "استراحت", IsWordSolved: false, IsHintBought: false, Hint: "خستگی رو از بین میبره" },
  { word: "آرامش", IsWordSolved: false, IsHintBought: false, Hint: "وقتی داشته باشیش حالت خوبه" },
  { word: "مزار", IsWordSolved: false, IsHintBought: false, Hint: "خدا مرده هاتو بیامرزه" },
  { word: "شهید", IsWordSolved: false, IsHintBought: false, Hint: "کسی که جونشو فدا کرده" },
];
let Lvl8 = [
  { word: "تابلو", IsWordSolved: false, IsHintBought: false, Hint: "تو جاده ها زیاد ازش هست" },
  { word: "شمشیر", IsWordSolved: false, IsHintBought: false, Hint: "برنده است" },
  { word: "زوبین", IsWordSolved: false, IsHintBought: false, Hint: "از کمان پرتاب میشه" },
  { word: "تفنگ", IsWordSolved: false, IsHintBought: false, Hint: "صدای زیادی تولید میکنه" },
  { word: "کلاشینکف", IsWordSolved: false, IsHintBought: false, Hint: "یه نوع تفنگ" },
  { word: "یخچال", IsWordSolved: false, IsHintBought: false, Hint: "داخلش خیلی سرده" },
  { word: "کولاک", alt: "شیاد-شیدا", IsWordSolved: false, IsHintBought: false, Hint: "برف شدید" },
  { word: "شادی", alt: "شیاد-شیدا", IsWordSolved: false, IsHintBought: false, Hint: "حال خوب ؟" },
  { word: "تولد", alt: "دولت", IsWordSolved: false, IsHintBought: false, Hint: "هر سال جشنش میگیری" },
  { word: "آزادی", IsWordSolved: false, IsHintBought: false, Hint: "در بند نبودن" },
];
let Lvl9 = [
  { word: "عاشق", IsWordSolved: false, IsHintBought: false, Hint: "کسی که دست از پا نمیشناسه" },
  { word: "شارژر", IsWordSolved: false, IsHintBought: false, Hint: "به گوشی وصل میشه" },
  { word: "اینترنت", IsWordSolved: false, IsHintBought: false, Hint: "صبح تا شب ازش استفاده میکنی" },
  { word: "اتاق", IsWordSolved: false, IsHintBought: false, Hint: "توش میخوابی" },
  { word: "طاقچه", IsWordSolved: false, IsHintBought: false, Hint: "فرو رفتگی داخل دیوار" },
  { word: "ساعت", IsWordSolved: false, IsHintBought: false, Hint: "عقربه داره" },
  { word: "شیشه", IsWordSolved: false, IsHintBought: false, Hint: "شفافه" },
  { word: "درخت", IsWordSolved: false, IsHintBought: false, Hint: "ریه های زمینن" },
  { word: "خرما", IsWordSolved: false, IsHintBought: false, Hint: "میوه قهوه ای رنگ" },
  { word: "ورزش", IsWordSolved: false, IsHintBought: false, Hint: "سبب تندرستی" },
];
let Lvl10 = [
  { word: "کیبورد", IsWordSolved: false, IsHintBought: false, Hint: "باهاش تایپ میکنی" },
  { word: "کارتن", alt: "تانکر", IsWordSolved: false, IsHintBought: false, Hint: "وسایل رو میذاری توش" },
  { word: "بطری", IsWordSolved: false, IsHintBought: false, Hint: "توش نوشیدنی میخوری" },
  { word: "باتری", IsWordSolved: false, IsHintBought: false, Hint: "برق رو ذخیره میکنه" },
  { word: "لیوان", IsWordSolved: false, IsHintBought: false, Hint: "اینم باهاش نوشیدنی میخوری" },
  { word: "استیل", IsWordSolved: false, IsHintBought: false, Hint: "به فارسی میشه فولاد" },
  { word: "پلاستیک", IsWordSolved: false, IsHintBought: false, Hint: "از نفت درست میشه" },
  { word: "فندک", IsWordSolved: false, IsHintBought: false, Hint: "آتیش درست میکنه" },
  { word: "شلوار", IsWordSolved: false, IsHintBought: false, Hint: "پوشیدنیه" },
  { word: "فلاکس", IsWordSolved: false, IsHintBought: false, Hint: "چایی توشه" },
];
let Lvl11 = [
  { word: "موشواره", IsWordSolved: false, IsHintBought: false, Hint: "به کامپیوتر ربط داره" },
  { word: "مانیتور", IsWordSolved: false, IsHintBought: false, Hint: "چیز هارو نشون میده" },
  { word: "مادربرد", IsWordSolved: false, IsHintBought: false, Hint: "قطعات کامپیوتر روش سوار میشن" },
  { word: "پردازنده", IsWordSolved: false, IsHintBought: false, Hint: "سی پی یو" },
  { word: "کتاب", IsWordSolved: false, IsHintBought: false, Hint: "با سوادت میکنه" },
  { word: "سبد", IsWordSolved: false, IsHintBought: false, Hint: "تو فروشگاه ها هست" },
  { word: "دفتر", IsWordSolved: false, IsHintBought: false, Hint: "توش مینویسی" },
  { word: "خودکار", IsWordSolved: false, IsHintBought: false, Hint: "باهاش مینویسی" },
  { word: "چاقو", IsWordSolved: false, IsHintBought: false, Hint: "دستتو میبره" },
  { word: "آشپزخانه", IsWordSolved: false, IsHintBought: false, Hint: "توی هر خونه هست" },
];
let Lvl12 = [
  { word: "چوبی", IsWordSolved: false, IsHintBought: false, Hint: "راهنما نمیخواد آسونه" },
  { word: "پوزبند", IsWordSolved: false, IsHintBought: false, Hint: "میبندی دور صورتت" },
  { word: "شال", IsWordSolved: false, IsHintBought: false, Hint: "میندازی دور گردنت" },
  { word: "دیوار", alt: "رادیو-داوری", IsWordSolved: false, IsHintBought: false, Hint: "بین دو تا مکان حصار میندازه" },
  { word: "سفید", IsWordSolved: false, IsHintBought: false, Hint: "گچ چه رنگیه؟" },
  { word: "پنجره", IsWordSolved: false, IsHintBought: false, Hint: "بیرون رو ازش میبینی" },
  { word: "نورگیر", IsWordSolved: false, IsHintBought: false, Hint: "محل نگهداری گل و گیاه در خانه" },
  { word: "گلدان", IsWordSolved: false, IsHintBought: false, Hint: "محل کاشت گل و گیاه" },
  { word: "کود", IsWordSolved: false, IsHintBought: false, Hint: "هم شیمیایی داریم هم حیوانی" },
  { word: "گیاه", IsWordSolved: false, IsHintBought: false, Hint: "توی گل رشد میکنه" },
];
let Lvl13 = [
  { word: "کاناپه", IsWordSolved: false, IsHintBought: false, Hint: "روش لم میدی" },
  { word: "موزاییک", IsWordSolved: false, IsHintBought: false, Hint: "توی کف خونه است" },
  { word: "فریزر", IsWordSolved: false, IsHintBought: false, Hint: "برای نگهداری غذا و نمونه آزمایشگاهی" },
  { word: "تلویزیون", IsWordSolved: false, IsHintBought: false, Hint: "باهاش اخبار و فیلم میبینی" },
  { word: "مبلمان", IsWordSolved: false, IsHintBought: false, Hint: "اینم مثل کاناپه است" },
  { word: "فروشگاه", IsWordSolved: false, IsHintBought: false, Hint: "ازش خرید میکنی" },
  { word: "بنگاه", IsWordSolved: false, IsHintBought: false, Hint: "جای آدم های کلکباز و سودجو" },
  { word: "لنج", alt: "لجن", IsWordSolved: false, IsHintBought: false, Hint: "تو دریا حرکت میکنه" },
  { word: "استان", IsWordSolved: false, IsHintBought: false, Hint: "بخشی از کشور" },
  { word: "روستا", alt: "ساتور", IsWordSolved: false, IsHintBought: false, Hint: "کوچکتر از شهر" },
];
let Lvl14 = [
  { word: "پولدار", IsWordSolved: false, IsHintBought: false, Hint: "کسی که پول داره" },
  { word: "کودک", IsWordSolved: false, IsHintBought: false, Hint: "کسی که سنش کمه" },
  { word: "همسر", alt: "سرمه", IsWordSolved: false, IsHintBought: false, Hint: "کسی که باهاش ازدواج میکنی" },
  { word: "باشگاه", IsWordSolved: false, IsHintBought: false, Hint: "جایی که ورزش میکنی" },
  { word: "کیسه", IsWordSolved: false, IsHintBought: false, Hint: "توش چیز میذاری" },
  { word: "دمبل", alt: "مبدل", IsWordSolved: false, IsHintBought: false, Hint: "توی باشگاه پیدا میشه" },
  { word: "بدنسازی", IsWordSolved: false, IsHintBought: false, Hint: "یه نوع ورزشه" },
  { word: "لامپ", IsWordSolved: false, IsHintBought: false, Hint: "سبب روشنایی" },
  { word: "چراغ", IsWordSolved: false, IsHintBought: false, Hint: "مترادف لامپ" },
  { word: "مهتابی", IsWordSolved: false, IsHintBought: false, Hint: "اینم نور درست میکنه" },
];
let Lvl15 = [
  { word: "پنکه", IsWordSolved: false, IsHintBought: false, Hint: "قبلا که کولر نبود از این استفاده میکردن" },
  { word: "آدمک", IsWordSolved: false, IsHintBought: false, Hint: "آدم کوچیک" },
  { word: "گهواره", IsWordSolved: false, IsHintBought: false, Hint: "ز   تا گور دانش بجوی..." },
  { word: "پوشاک", IsWordSolved: false, IsHintBought: false, Hint: "پوشیدنی" },
  { word: "خوراک", IsWordSolved: false, IsHintBought: false, Hint: "خوردنی" },
  { word: "خیابان", IsWordSolved: false, IsHintBought: false, Hint: "یه بخشی از شهر " },
  { word: "بوستان", IsWordSolved: false, IsHintBought: false, Hint: "مترادف پارک" },
  { word: "زنگوله", IsWordSolved: false, IsHintBought: false, Hint: "به گوسفند ها میبندن" },
  { word: "گوسفند", IsWordSolved: false, IsHintBought: false, Hint: "حیوونه" },
  { word: "نهنگ", IsWordSolved: false, IsHintBought: false, Hint: "توی دریاست" },
];
